apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: Hugging Face Detector ServingRuntime for KServe
    opendatahub.io/template-name: guardrails-detector-huggingface-serving-template
    openshift.io/display-name: Hugging Face Detector ServingRuntime for KServe
  name: deberta-v3-base-prompt-injection-v2
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8000'
  containers:
    - args:
        - '--workers=1'
        - '--host=0.0.0.0'
        - '--port=8000'
        - '--log-config=/common/log_conf.yaml'
      command:
        - uvicorn
        - 'app:app'
      env:
        - name: MODEL_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: DETECTOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      image: 'registry.redhat.io/rhoai/odh-guardrails-detector-huggingface-runtime-rhel9@sha256:4ffac83c0a88d3ad6b920b6a21e3e165d6e50b6470ca2695deb4e16537960623'
      name: kserve-container
      ports:
        - containerPort: 8000
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: guardrails-detector-hf-runtime
