kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-nlp
data:
  config.yaml: |
    detectors:
      regex:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap:
        type: text_contents
        service:
          hostname: granite-guardian-hap-38m-predictor
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      prompt_injection:
        type: text_contents
        service:
          hostname: deberta-v3-base-prompt-injection-v2-predictor
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"
  enableBuiltInDetectors: true
  enableGuardrailsGateway: false
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: guardrails-detector-service
spec:
  selector:
    app: guardrails-orchestrator
    component: guardrails-orchestrator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
